In [5]:
import numpy as np
x = np.array([[1, 2, 3], [4, 5, 6]])
print("type of array",type(x))
y=list(range(10))
print(y)
print("type of array",type(y))

type of array <class 'numpy.ndarray'>
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
type of array <class 'list'>


In [12]:
L2 = [str(c) for c in y]
L2
print("type of L2 first element",type(L2[0]))


type of L2 first element <class 'str'>


In [15]:
a = [True, "2", 3.0, 4] 
[type(item) for item in a]

[bool, str, float, int]

In [21]:
import array
h=list(range(10))
print(type(h))
H=array.array('i',h)
print(type(H))

<class 'list'>
<class 'array.array'>


In [32]:
g=np.array([1,2,3,4],dtype="float32")
print(g)
g1=np.array([range(i,i+3) for i in [2,3,4]])
print(g1)

[ 1.  2.  3.  4.]
[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [42]:
k1=np.zeros(10,dtype=int)
print(k1,"\n")
k2=np.ones((3,5),dtype=float)
print(k2,"\n")
k3=np.full((3, 5), 3.14)
print(k3,"\n")

[0 0 0 0 0 0 0 0 0 0] 

[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]] 

[[ 3.14  3.14  3.14  3.14  3.14]
 [ 3.14  3.14  3.14  3.14  3.14]
 [ 3.14  3.14  3.14  3.14  3.14]] 



In [62]:
o=np.arange(0,20,3)#start,stop,steps
print(o)
o1=np.linspace(0,1,5) # Create an array of five values evenly spaced between 0 and 1
print("\n",o1)
o2=np.random.random((3,3))
print("\n",o2)
o3=np.random.normal(0,1,(3,3))
print("\n",o3)
o4=np.random.randint(0,10,(3,3))
print("\n",o4)
o5=np.eye(3)
print("\n",o5)
o6=np.empty(3)
print("\n",o6)


[ 0  3  6  9 12 15 18]

 [ 0.    0.25  0.5   0.75  1.  ]

 [[ 0.21510899  0.04505155  0.21434358]
 [ 0.37918186  0.2573244   0.94725922]
 [ 0.88553125  0.65174339  0.62177421]]

 [[ 1.01242275  0.23266908 -1.13827128]
 [-1.2680374  -0.88201151 -0.85219115]
 [ 1.09137402 -1.87995968 -0.09921542]]

 [[8 5 6]
 [3 0 7]
 [1 5 0]]

 [[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]

 [ 1.  1.  1.]


In [72]:
z=np.random.randint(0,10,size=6)
print("the number of dimensions:  ",z.ndim,"\n the size of each dimension: "
      ,z.shape,"\n the total size of the array: ",z.size)
z1=np.random.randint(0,10,size=(3,4))
print("\n\nthe number of dimensions:  ",z1.ndim,"\n the size of each dimension: "
      ,z1.shape,"\n the total size of the array: ",z1.size)

z2=np.random.randint(0,10,size=(3,4,5))
print("\n\nthe number of dimensions:  ",z2.ndim,"\n the size of each dimension: "
      ,z2.shape,"\n the total size of the array: ",z2.size)

print("\ndtype:",z2.dtype)
print("itemsize:", z2.itemsize, "bytes")
print("nbytes:", z2.nbytes, "bytes")


the number of dimensions:   1 
 the size of each dimension:  (6,) 
 the total size of the array:  6


the number of dimensions:   2 
 the size of each dimension:  (3, 4) 
 the total size of the array:  12


the number of dimensions:   3 
 the size of each dimension:  (3, 4, 5) 
 the total size of the array:  60

dtype: int64
itemsize: 8 bytes
nbytes: 480 bytes


In [84]:
t=np.arange(10)
print(t)
print(t[4:9])
print(t[::-1])#start,stop,steps

t2=np.arange([10,10])
print("2d",t2)

[0 1 2 3 4 5 6 7 8 9]
[4 5 6 7 8]
[9 8 7 6 5 4 3 2 1 0]


TypeError: unsupported operand type(s) for -: 'list' and 'int'